export const SET_NEW_PASSWORD = "SET_NEW_PASSWORD";
export const SAFE_BOX_LOCKING = "SAFE_BOX_LOCKING";
export const SAFE_BOX_LOCKED = "SAFE_BOX_LOCKED";
export const SET_IDLE_STATE = "SET_IDLE_STATE";
export const SAFE_BOX_UNLOCKED = "SAFE_BOX_UNLOCKED";
export const SAFE_BOX_UNLOCKING = "SAFE_BOX_UNLOCKING";
export const SAFE_BOX_ERROR = "SAFE_BOX_ERROR";
export const ACTIVATE_SERVICE_MODE = "ACTIVATE_SERVICE_MODE";
export const MASTER_CODE_VALIDATING = "MASTER_CODE_VALIDATING";
export const VALIDATION_SUCCESSFULL = "VALIDATION_SUCCESSFULL";
export const MASTER_CODE_VALIDATION_SUCCESSFULL =
  "MASTER_CODE_VALIDATION_SUCCESSFULL";
